{
 "title": "Simple Mint API Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(total_requests[1m])", "legendFormat": "Total" },
    { "expr": "rate(successful_requests[1m])", "legendFormat": "Successful" },
    { "expr": "rate(failed_requests[1m])", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Success & Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(sum(rate(successful_requests[10m])) / sum(rate(total_requests[10m]))) * 100",
     "legendFormat": "Success Rate"
    },
    {
     "expr": "(sum(rate(failed_requests[10m])) / sum(rate(total_requests[10m]))) * 100",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Average Duration of Successful Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(mint_request_duration_in_sec_sum[1m]) / rate(mint_request_duration_in_sec_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}