[package]
name = "action_queue"
edition = "2024"         # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]

# Read more about the package management system options:
# https://docs.sui.io/guides/developer/sui-101/move-package-management
